import { useEffect,useState } from 'react';
import { Plus,RotateCcw,Save,TestTube2,Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { deleteJson,getJson,postJson,type RegexRuleItem,type RegexTestResult } from '@/api';
import { Button } from '@/components/ui/button';import { Card,CardHeader,CardTitle } from '@/components/ui/card';import { Input } from '@/components/ui/input';import { Label } from '@/components/ui/label';
const defaultPattern='(?<![A-Za-z0-9])(?=[A-Za-z0-9]{4,8}(?![A-Za-z0-9]))(?=[A-Za-z0-9]*[0-9])[A-Za-z0-9]+(?![A-Za-z0-9])';
const blank=():RegexRuleItem=>({id:0,name:'New rule',enabled:true,contextKeywords:['verification code'],pattern:defaultPattern,description:'',priority:100});
export function RegexRulesPage():JSX.Element{const[rules,setRules]=useState<RegexRuleItem[]>([]);const[editing,setEditing]=useState<RegexRuleItem|null>(null);const[sample,setSample]=useState('Your verification code is 583921');const[result,setResult]=useState<RegexTestResult|null>(null);const load=()=>getJson<{rules:RegexRuleItem[]}>('/api/admin/regex-rules').then(x=>setRules(x.rules)).catch((e:unknown)=>toast.error(e instanceof Error?e.message:'Unable to load rules'));useEffect(()=>{void load();},[]);
const payload=(r:RegexRuleItem)=>({name:r.name,enabled:r.enabled,contextKeywords:r.contextKeywords,pattern:r.pattern,description:r.description,priority:r.priority});
const save=()=>{if(!editing)return;postJson(editing.id?`/api/admin/regex-rules/${editing.id}`:'/api/admin/regex-rules',payload(editing)).then(()=>{toast.success('Regex rule saved');setEditing(null);load();}).catch((e:unknown)=>toast.error(e instanceof Error?e.message:'Save failed'));};
return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Regex Rules</h2><p className="text-xs text-muted-foreground">Context-aware rules run before optional AI fallback.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>{if(confirm('Replace all rules with shipped defaults?'))postJson('/api/admin/regex-rules/reset').then(()=>{setEditing(null);load();toast.success('Defaults restored');});}}><RotateCcw className="mr-2 h-4 w-4"/>Reset defaults</Button><Button onClick={()=>setEditing(blank())}><Plus className="mr-2 h-4 w-4"/>Add rule</Button></div></div>
<div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><Card className="p-5"><CardHeader className="p-0 pb-3"><CardTitle>Rules</CardTitle></CardHeader><div className="space-y-2">{rules.map(r=><button key={r.id} onClick={()=>{setEditing({...r});setResult(null);}} className="w-full rounded-lg border border-border p-3 text-left hover:bg-muted"><div className="flex justify-between"><span className="font-medium">{r.name}</span><span className="text-xs text-muted-foreground">{r.enabled?'Enabled':'Disabled'} · {r.priority}</span></div><div className="mt-1 truncate font-mono text-xs text-muted-foreground">{r.pattern}</div></button>)}</div></Card>
<Card className="p-5">{editing?<div className="space-y-4"><CardHeader className="p-0"><CardTitle>{editing.id?'Edit rule':'New rule'}</CardTitle></CardHeader><label className="flex gap-2 text-sm"><input type="checkbox" checked={editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/>Enabled</label><div><Label>Name</Label><Input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></div><div><Label>Context keywords (one per line)</Label><textarea className="mt-1 min-h-28 w-full rounded-md border border-input bg-background p-2 text-sm" value={editing.contextKeywords.join('\n')} onChange={e=>setEditing({...editing,contextKeywords:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/></div><div><Label>Regex pattern</Label><Input className="font-mono" value={editing.pattern} onChange={e=>setEditing({...editing,pattern:e.target.value})}/></div><div><Label>Description</Label><Input value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></div><div><Label>Priority (lower runs first)</Label><Input type="number" value={editing.priority} onChange={e=>setEditing({...editing,priority:Number(e.target.value)||100})}/></div><div className="flex gap-2"><Button onClick={save}><Save className="mr-2 h-4 w-4"/>Save</Button>{editing.id?<Button variant="destructive" onClick={()=>{if(confirm('Delete this rule?'))deleteJson(`/api/admin/regex-rules/${editing.id}`).then(()=>{setEditing(null);load();});}}><Trash2 className="mr-2 h-4 w-4"/>Delete</Button>:null}</div><hr className="border-border"/><div><Label>Test text</Label><textarea className="mt-1 min-h-28 w-full rounded-md border border-input bg-background p-2 text-sm" value={sample} onChange={e=>setSample(e.target.value)}/><Button variant="outline" className="mt-2" onClick={()=>postJson<RegexTestResult>('/api/admin/regex-rules/test',{rule:payload(editing),body:sample}).then(setResult).catch((e:unknown)=>toast.error(e instanceof Error?e.message:'Test failed'))}><TestTube2 className="mr-2 h-4 w-4"/>Test rule</Button>{result?<div className="mt-3 rounded-lg border border-border p-3 text-sm">{result.matched?<><div>Matched: <b>{result.code}</b></div><div className="mt-1 text-xs text-muted-foreground">{result.contextExcerpt}</div></>:<div>No match</div>}</div>:null}</div></div>:<div className="text-sm text-muted-foreground">Select a rule or add a new one.</div>}</Card></div></div>;
}
